Dev
ClevertecFrontendLab/sprint1-yasinskydew pull request #1
Opened 2023-01-31 12:20 UTC by yasinskydew

2023-01-31 12:24 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675167851/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675167851/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675167851/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675167851/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675167851/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675167851/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675167851/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675167851/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675167851/content-window.png)

2023-01-31 12:56 UTC, klichkovskiy requested changes

2023-01-31 12:56 UTC, klichkovskiy commented on src/components/main-controls/main-controls.tsx
> +            <div className={classes.controlsViewMode}>
![image](https://user-images.githubusercontent.com/62481116/215764783-7461b3f9-863f-449c-9058-88b7a75837ac.png)
Сделай кнопки по макету

2023-01-31 12:56 UTC, klichkovskiy commented on src/pages/use-terms/use-terms-page.tsx
> +import React, {FC} from 'react';
А зачем ты React импортируешь каждый раз? Удаляй этот импорт

2023-01-31 12:56 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +import {BookCard, BookCardMode} from '../../components/book/book_card/book-card';
![image](https://user-images.githubusercontent.com/62481116/215765184-ad9f5b61-8bb5-4597-8778-48b2573ce925.png)
Убери отсутствие отступов

2023-01-31 12:56 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +import {BookCard, BookCardMode} from '../../components/book/book_card/book-card';
Это что?
![image](https://user-images.githubusercontent.com/62481116/215765359-9470c919-177b-4fad-a79d-8cbc360e6f2a.png)

2023-01-31 12:56 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +import {BookCard, BookCardMode} from '../../components/book/book_card/book-card';
Сделай по макету
![image](https://user-images.githubusercontent.com/62481116/215765429-801fafca-64a2-46db-884e-41dfbc9ff6d9.png)

2023-01-31 12:56 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +import {BookCard, BookCardMode} from '../../components/book/book_card/book-card';
Пересмотри всю верстку
![image](https://user-images.githubusercontent.com/62481116/215765544-d1bd1b2c-b0b8-4596-b149-57c8197d741b.png)

2023-01-31 12:56 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +import {BookCard, BookCardMode} from '../../components/book/book_card/book-card';
Даже скролл есть
![image](https://user-images.githubusercontent.com/62481116/215765623-e6a6232c-96f5-4a41-a570-b745d2d13c34.png)

2023-01-31 12:56 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +    const user: IUser = {
Это тут что делает? Все константы в отдельных файлах лежат

2023-01-31 12:56 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +        <section className={[classes.bookPage, classes.container].join(' ')}>
![image](https://user-images.githubusercontent.com/62481116/215765844-7e466c63-1960-41f0-b148-0af2d0993d6e.png)
Пересмотри всю верстку

2023-01-31 15:06 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675177600/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675177600/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675177600/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675177600/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675177600/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675177600/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675177600/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675177600/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675177600/content-window.png)

2023-01-31 15:08 UTC, yasinskydew commented
запушил, случайно, пока не всё поправлено

2023-01-31 15:34 UTC, klichkovskiy requested changes
Доделывай.

2023-01-31 15:34 UTC, klichkovskiy commented on src/types/types.tsx
> +type _Range<T extends number, R extends unknown[]> = R['length'] extends T ? R[number] : _Range<T, [R['length'], ...R]>;
А чего этот файл tsx он же ничего не возвращает такого

2023-02-01 11:34 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675251289/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675251289/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675251289/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675251289/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675251289/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675251289/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675251289/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675251289/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675251289/content-window.png)

2023-02-01 11:41 UTC, klichkovskiy requested changes

2023-02-01 11:41 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +export const BookPage:FC = () => {
![image](https://user-images.githubusercontent.com/62481116/216032560-9b2963b8-4efd-41a4-9e8b-4d25723e146b.png)
Убери скрол

2023-02-01 11:41 UTC, klichkovskiy commented on src/components/main-controls/main-controls.tsx
> +export const MainControls = () => {
![image](https://user-images.githubusercontent.com/62481116/216032909-ac601719-ab5f-4a9c-8195-78ccd09f1c54.png)
Переделай

2023-02-01 11:41 UTC, klichkovskiy commented on src/components/main-controls/main-controls.tsx
> +export const MainControls = () => {
![image](https://user-images.githubusercontent.com/62481116/216033007-70738743-b30c-4516-850e-93d298b895f0.png)
И это

2023-02-01 11:51 UTC, yasinskydew commented on src/components/main-controls/main-controls.tsx
> +export const MainControls = () => {
что конкретней нужно сделать

2023-02-01 12:34 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675254879/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675254879/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675254879/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675254879/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675254879/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675254879/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675254879/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675254879/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675254879/content-window.png)

2023-02-01 12:45 UTC, klichkovskiy requested changes

2023-02-01 12:45 UTC, klichkovskiy commented on src/index.tsx
> +root.render(
Все еще есть места с горизонтальным скролом. Убери их и будем апрувится

2023-02-01 15:29 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675265399/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675265399/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675265399/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675265399/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675265399/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675265399/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675265399/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675265399/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/yasinskydew/1675265399/content-window.png)

2023-02-01 15:45 UTC, klichkovskiy approved these changes

2023-02-01 15:51 UTC, merged